engines:
	stylelint:
		enabled: true
	tslint:
		enabled: true
		path: 'IdentityServer/ClientApp/tsling.json'
		exclude_paths:
			- 'IdentityServer/ClientApp/e2e/**/*'
	sonarscharp:
		enabled: true
		exclude_paths:
			- 'IdentityServer.Infrastructure/Migrations/**/*'

